// GENERATED by tools/gen-manifest.mjs — do not edit by hand.
// The level list is the src/levels/ directory; order comes from each
// level's `order` field. Run `npm run levels` after adding a file.
import L0 from "./sh01-first-arc.json" with { type: "json" };
import L1 from "./sh02-the-span.json" with { type: "json" };
import L2 from "./sh03-sporefall.json" with { type: "json" };
import L3 from "./sh04-undertow.json" with { type: "json" };
import L4 from "./sh05-reaper-below.json" with { type: "json" };
import L5 from "./m01-cave-mouth.json" with { type: "json" };
import L6 from "./m02-the-prospect.json" with { type: "json" };
import L7 from "./m03-the-descent.json" with { type: "json" };
import L8 from "./m04-deep-gallery.json" with { type: "json" };
import L9 from "./m05-crushing-way.json" with { type: "json" };
import L10 from "./m06-gate-below.json" with { type: "json" };
import L11 from "./m07-baphomet.json" with { type: "json" };
import L12 from "./i01-the-threshold.json" with { type: "json" };
import L13 from "./i02-sinking-fields.json" with { type: "json" };
import L14 from "./i03-the-geysers.json" with { type: "json" };
import L15 from "./i04-arcs-of-ash.json" with { type: "json" };
import L16 from "./i05-the-crucible.json" with { type: "json" };
import L17 from "./i06-last-descent.json" with { type: "json" };
import L18 from "./i07-leviathan.json" with { type: "json" };

export const LEVELS_DATA = [L0, L1, L2, L3, L4, L5, L6, L7, L8, L9, L10, L11, L12, L13, L14, L15, L16, L17, L18];
